version: 0.0
os: linux
files:
  - source: ./docker-compose-prod.yml
    destination: /home/ubuntu/
  - source: scripts
    destination: /home/ubuntu/scripts
  
hooks:
  ApllicationStop:
    - location: ./scripts/application-stop.sh
      timeout: 100000
  AfterInstall:
    - location: ./scripts/after-install.sh
      timeout: 200000
  ApplicationStart:
    - location: ./scripts/application-start.sh
      timeout: 3000
  ValidateService:
    - location: ./scripts/validate-service.sh
      timeout: 3000